// Articles
export const GET_DATA_WAITING = "GET_DATA_WAITING"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAILED = "GET_DATA_FAILED"
// Bookmark
export const BOOKMARK_ITEM = 'BOOKMARK_ITEM';
export const UNBOOKMARK_ITEM = 'UNBOOKMARK_ITEM';
export const GET_BOOKMARK_ITEMS = 'GET_BOOKMARK_ITEMS';

